Logging started at 08:41:16 on 30 Sep 2014
QIIME version: 1.8.0-dev

qiime_config values:
pynast_template_alignment_fp	/Users/jc33/dependencies/data/core_set_aligned.fasta.imputed
seconds_to_sleep	2
torque_queue	friendlyq
jobs_to_start	1
cloud_environment	False
denoiser_min_per_core	50
assign_taxonomy_id_to_taxonomy_fp	/Users/jc33/.virtualenvs/qiime/gg_13_5_otus/taxonomy/97_otu_taxonomy.txt
temp_dir	/tmp/
blastall_fp	/Users/jc33/blast-2.2.22/bin
python_exe_fp	python
sc_queue	all.q
assign_taxonomy_reference_seqs_fp	/Users/jc33/.virtualenvs/qiime/gg_13_5_otus/rep_set/97_otus.fasta
qiime_scripts_dir	/Users/jc33/.virtualenvs/qiime2/bin

parameter file values:

Input file md5 sums:
../row_2_3_comps/output/row_23_filtered_800_table.biom: f3a172651afdf3d8665153b10dc8efd8
/Users/jc33/google_drive/thesis/thesis/analyses/thesis_analyses/master_period_1-2-3_map_5182014.txt: 0072a9fe25868c3cbc1cf2bbc15b97ee

Executing commands.

# Summarize OTU table by Category command 
summarize_otu_by_cat.py -m /Users/jc33/google_drive/thesis/thesis/analyses/thesis_analyses/master_period_1-2-3_map_5182014.txt -i ../row_2_3_comps/output/row_23_filtered_800_table.biom -o ../row_2_3_comps/output/Row_otu_table.biom -c 'Row' 

Stdout:

Stderr:

# Summarize Taxonomy command 
summarize_taxa.py -i ../row_2_3_comps/output/Row_otu_table.biom -o ../row_2_3_comps/output/ 

Stdout:

Stderr:

# Plot Taxonomy Summary command 
plot_taxa_summary.py -i ../row_2_3_comps/output/Row_otu_table_L2.txt,../row_2_3_comps/output/Row_otu_table_L3.txt,../row_2_3_comps/output/Row_otu_table_L4.txt,../row_2_3_comps/output/Row_otu_table_L5.txt,../row_2_3_comps/output/Row_otu_table_L6.txt -o ../row_2_3_comps/output//taxa_summary_plots/ 



*** ERROR RAISED DURING STEP: Plot Taxonomy Summary
Command run was:
 plot_taxa_summary.py -i ../row_2_3_comps/output/Row_otu_table_L2.txt,../row_2_3_comps/output/Row_otu_table_L3.txt,../row_2_3_comps/output/Row_otu_table_L4.txt,../row_2_3_comps/output/Row_otu_table_L5.txt,../row_2_3_comps/output/Row_otu_table_L6.txt -o ../row_2_3_comps/output//taxa_summary_plots/ 
Command returned exit status: 1
Stdout:

Stderr
Traceback (most recent call last):
  File "/Users/jc33/.virtualenvs/qiime-dev/bin/plot_taxa_summary.py", line 301, in <module>
    main()
  File "/Users/jc33/.virtualenvs/qiime-dev/bin/plot_taxa_summary.py", line 297, in main
    resize_nth_label, label_type, include_html_legend, include_html_counts)
  File "/Users/jc33/.virtualenvs/qiime-dev/lib/python2.7/site-packages/qiime/plot_taxa_summary.py", line 1152, in make_all_charts
    'When generating area charts, the number of samples (or category values) must be greater than 1.  However, you can still produce a pie chart or bar chart with only 1 sample (or category value), but you must remove the area chart value from the input arguments.')
ValueError: When generating area charts, the number of samples (or category values) must be greater than 1.  However, you can still produce a pie chart or bar chart with only 1 sample (or category value), but you must remove the area chart value from the input arguments.


Logging stopped at 08:55:41 on 30 Sep 2014
